# Generated by Django 5.2 on 2025-08-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='no_hp',
            new_name='no_telp',
        ),
    ]
