# Generated by Django 5.2 on 2025-08-14 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_rename_no_hp_anggota_no_telp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='tgl_daftar',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
