# Generated by Django 5.2 on 2025-08-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_alter_anggota_tgl_daftar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='tgl_daftar',
            new_name='tanggal_daftar',
        ),
    ]
