# Generated by Django 5.2 on 2025-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenispinjaman',
            name='nama_jenis',
            field=models.CharField(choices=[('Reguler', 'Reguler'), ('Khusus', 'Khusus'), ('Barang', 'Barang')], max_length=50),
        ),
    ]
