# Generated by Django 5.2.1 on 2025-08-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0003_kategorijasa_remove_jenispinjaman_jasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorijasa',
            name='kategori_jasa',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
