# Generated by Django 5.2 on 2025-08-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0007_alter_pinjaman_jatuh_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjaman',
            name='jasa',
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='jasa_persen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='jasa_rupiah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
