# Generated by Django 5.2 on 2025-09-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0008_remove_pinjaman_jasa_pinjaman_jasa_persen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angsuran',
            old_name='id_angsur',
            new_name='id_pembayaran',
        ),
    ]
