# Generated by Django 5.2.1 on 2025-08-21 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_koperasi', '0002_alter_admin_role_alter_admin_username'),
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSimpanan',
            fields=[
                ('id_jenis_simpanan', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(choices=[('Wajib', 'Wajib'), ('Sukarela', 'Sukarela'), ('Pokok', 'Pokok')], max_length=50)),
            ],
            options={
                'db_table': 'Jenis_Simpanan',
            },
        ),
        migrations.CreateModel(
            name='Simpanan',
            fields=[
                ('id_simpanan', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal_menyimpan', models.DateField()),
                ('jumlah_menyimpan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_koperasi.admin')),
                ('id_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('id_jenis_simpanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
            ],
            options={
                'db_table': 'Simpanan',
            },
        ),
    ]
