# Generated by Django 5.2.1 on 2025-08-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0002_alter_admin_role_alter_admin_username'),
        ('anggota', '0001_initial'),
        ('simpanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpanan',
            name='tanggal_menarik',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jenissimpanan',
            name='nama_jenis',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Penarikan',
            fields=[
                ('id_penarikan', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_penarikan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tanggal_penarikan', models.DateField()),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_koperasi.admin')),
                ('id_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('id_jenis_simpanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
            ],
            options={
                'db_table': 'Penarikan',
            },
        ),
    ]
