# Generated by Django 5.2.1 on 2025-08-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0002_simpanan_tanggal_menarik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penarikan',
            old_name='id_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='penarikan',
            old_name='id_anggota',
            new_name='anggota',
        ),
        migrations.RenameField(
            model_name='penarikan',
            old_name='id_jenis_simpanan',
            new_name='jenis_simpanan',
        ),
        migrations.RenameField(
            model_name='simpanan',
            old_name='id_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='simpanan',
            old_name='id_anggota',
            new_name='anggota',
        ),
        migrations.RenameField(
            model_name='simpanan',
            old_name='id_jenis_simpanan',
            new_name='jenis_simpanan',
        ),
        migrations.AlterField(
            model_name='jenissimpanan',
            name='nama_jenis',
            field=models.CharField(choices=[('POKOK', 'Simpanan Pokok'), ('WAJIB', 'Simpanan Wajib'), ('SUKARELA', 'Simpanan Sukarela')], max_length=50, unique=True),
        ),
    ]
