# Generated by Django 5.2 on 2025-08-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
