# Generated by Django 5.2 on 2025-08-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('bendahara', 'Bendahara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
