# Generated by Django 5.2.1 on 2025-09-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_koperasi', '0001_initial'),
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSimpanan',
            fields=[
                ('id_jenis_simpanan', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(choices=[('POKOK', 'Simpanan Pokok'), ('WAJIB', 'Simpanan Wajib'), ('SUKARELA', 'Simpanan Sukarela')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Jenis_Simpanan',
            },
        ),
        migrations.CreateModel(
            name='Penarikan',
            fields=[
                ('id_penarikan', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_penarikan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tanggal_penarikan', models.DateField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_koperasi.admin')),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('jenis_simpanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
            ],
            options={
                'db_table': 'Penarikan',
            },
        ),
        migrations.CreateModel(
            name='Simpanan',
            fields=[
                ('id_simpanan', models.BigAutoField(primary_key=True, serialize=False)),
                ('tanggal_menyimpan', models.DateField()),
                ('tanggal_menarik', models.DateField(blank=True, null=True)),
                ('jumlah_menyimpan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_koperasi.admin')),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('jenis_simpanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
            ],
            options={
                'db_table': 'Simpanan',
            },
        ),
    ]
