# Generated by Django 5.2 on 2025-08-15 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_koperasi', '0002_alter_admin_role_alter_admin_username'),
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPinjaman',
            fields=[
                ('id_jenis_pinjaman', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=100)),
                ('jasa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Jenis_Pinjaman',
            },
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id_pinjaman', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=18)),
                ('jatuh_tempo', models.DateField()),
                ('jasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('angsuran_per_bulan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tanggal_meminjam', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_koperasi.admin')),
                ('id_jenis_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjaman.jenispinjaman')),
                ('nomor_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
            ],
            options={
                'db_table': 'Pinjaman',
            },
        ),
        migrations.CreateModel(
            name='Angsuran',
            fields=[
                ('id_angsur', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tanggal_bayar', models.DateField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_koperasi.admin')),
                ('id_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjaman.pinjaman')),
            ],
            options={
                'db_table': 'Angsuran',
            },
        ),
    ]
