# Generated by Django 5.2.1 on 2025-09-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_koperasi', '0001_initial'),
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPinjaman',
            fields=[
                ('id_jenis_pinjaman', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(choices=[('Reguler', 'Reguler'), ('Khusus', 'Khusus'), ('Barang', 'Barang')], max_length=50)),
            ],
            options={
                'db_table': 'Jenis_Pinjaman',
            },
        ),
        migrations.CreateModel(
            name='KategoriJasa',
            fields=[
                ('id_kategori_jasa', models.BigAutoField(primary_key=True, serialize=False)),
                ('kategori_jasa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Kategori_Jasa',
            },
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id_pinjaman', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=18)),
                ('angsuran_per_bulan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('jasa_persen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jasa_rupiah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tanggal_meminjam', models.DateField()),
                ('jatuh_tempo', models.PositiveIntegerField(help_text='Lama pinjaman dalam bulan')),
                ('sisa_pinjaman', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(max_length=20)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_koperasi.admin')),
                ('id_jenis_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjaman.jenispinjaman')),
                ('id_kategori_jasa', models.ForeignKey(db_column='id_kategori_jasa', default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjaman.kategorijasa')),
                ('nomor_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
            ],
            options={
                'db_table': 'Pinjaman',
            },
        ),
        migrations.CreateModel(
            name='Angsuran',
            fields=[
                ('id_pembayaran', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tanggal_bayar', models.DateField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_koperasi.admin')),
                ('id_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjaman.pinjaman')),
            ],
            options={
                'db_table': 'Angsuran',
            },
        ),
    ]
