# Generated by Django 5.2 on 2025-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='angsuran',
            name='keterangan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
