# Generated by Django 5.2 on 2025-08-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0002_alter_jenispinjaman_nama_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjaman',
            name='lama_peminjaman',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pinjaman',
            name='angsuran_per_bulan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
