# Generated by Django 5.2 on 2025-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0002_angsuran_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angsuran',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='angsuran',
            name='tipe_bayar',
            field=models.CharField(choices=[('cicilan', 'Cicilan + Jasa'), ('jasa', 'Jasa Saja')], default='cicilan', max_length=10),
        ),
    ]
