# Generated by Django 5.2.1 on 2025-08-29 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0002_alter_jenispinjaman_nama_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriJasa',
            fields=[
                ('id_kategori_jasa', models.BigAutoField(primary_key=True, serialize=False)),
                ('kategori_jasa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Kategori_Jasa',
            },
        ),
        migrations.RemoveField(
            model_name='jenispinjaman',
            name='jasa',
        ),
        migrations.AddField(
            model_name='jenispinjaman',
            name='id_kategori_jasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjaman.kategorijasa'),
        ),
    ]
