# Generated by Django 5.2 on 2025-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0003_remove_angsuran_keterangan_angsuran_tipe_bayar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angsuran',
            name='tipe_bayar',
        ),
        migrations.AddField(
            model_name='angsuran',
            name='keterangan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
