# Generated by Django 5.2 on 2025-08-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0003_pinjaman_lama_peminjaman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenispinjaman',
            name='kategori_jasa',
            field=models.CharField(choices=[('flat', 'Flat'), ('turunan', 'Turunan')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='kategori_jasa',
            field=models.CharField(choices=[('flat', 'Flat'), ('turunan', 'Turunan')], default='flat', max_length=20),
        ),
    ]
