# Generated by Django 5.2.1 on 2025-08-29 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0004_alter_kategorijasa_kategori_jasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenispinjaman',
            name='id_kategori_jasa',
            field=models.ForeignKey(db_column='id_kategori_jasa', on_delete=django.db.models.deletion.CASCADE, to='pinjaman.kategorijasa'),
        ),
    ]
