# Generated by Django 5.2 on 2025-08-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0004_jenispinjaman_kategori_jasa_pinjaman_kategori_jasa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinjaman',
            old_name='jasa',
            new_name='jasa_persen',
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='jasa_pinjam',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
