# Generated by Django 5.2.1 on 2025-08-29 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0005_alter_jenispinjaman_id_kategori_jasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenispinjaman',
            name='id_kategori_jasa',
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='id_kategori_jasa',
            field=models.ForeignKey(db_column='id_kategori_jasa', default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjaman.kategorijasa'),
        ),
    ]
