# Generated by Django 5.2 on 2025-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0009_rename_id_angsur_angsuran_id_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjaman',
            name='sisa_pinjaman',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
