# Generated by Django 5.2.1 on 2025-09-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ketua', 'Ketua'), ('sekretaris', 'Sekretaris'), ('bendahara', 'Bendahara')], max_length=20)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
